Patch 1
howardwu/awesome-aleo pull request #56
Opened 2024-02-01 21:57 UTC by mwyatt896

Added the following Puzzle contributions:

- Where's Alex
- Treasure Hunt
- Super Leo Ligue
- Aleo Fortune
- Puzzle SDK for zkGames
- Puzzle Wallet
- Puzzle SDK
- Aleo Wallet Connect Standards
- iOS Swift Starter Kit

2024-02-07 00:27 UTC, collinc97 requested changes
Few nits. Thank you Puzzle team!

2024-02-07 00:27 UTC, collinc97 commented on README.md
> +- [Where's Alex](https://github.com/puzzlehq/wheres_alex) simple multiparty hidden information game - a game of hide and seek with Alex Pruden! The most forked game on Aleo built using Puzzle SDK for
```suggestion
- [Where's Alex](https://github.com/puzzlehq/wheres_alex) - A multiparty hidden information game on Aleo
```

2024-02-07 00:27 UTC, collinc97 commented on README.md
> +- [Treasure Hunt](https://treasures.puzzle.online/) multiparty hidden information game --built using Puzzle SDK for zkGames and Puzzle's game bot infrastructure
```suggestion
- [Treasure Hunt](https://treasures.puzzle.online/) - A multiparty hidden treasure hunt game on Aleo
```

2024-02-07 00:27 UTC, collinc97 commented on README.md
> +- [Super Leo Ligue](https://aleo-fortune.vercel.app/) Play classic roulette and more onchain -- built using Puzzle SDK for zkGames
```suggestion
- [Super Leo Ligue](https://aleo-fortune.vercel.app/) - Play classic casino games like roulette and more on Aleo
```

2024-02-07 00:27 UTC, collinc97 commented on README.md
> +- [Aleo Fortune](https://superleolig.vercel.app/) challenge a friend to an onchain soccer game with hidden strategies -- built using Puzzle SDK for zkGames
```suggestion
- [Aleo Fortune](https://superleolig.vercel.app/) - Challenge a friend to an onchain soccer game with hidden strategies
```

2024-02-07 00:27 UTC, collinc97 commented on README.md
> +- [Puzzle SDK for zkGames](https://docs.puzzle.online/tutorials/build_your_first_zkgame/) purpose built SDK for building multiparty hidden information games on Aleo by the Puzzle Wallet team
```suggestion
- [Puzzle SDK for zkGames](https://docs.puzzle.online/tutorials/build_your_first_zkgame/) - A SDK for building multiparty hidden information games on Aleo
```

2024-02-15 02:18 UTC, howardwu approved these changes

2024-02-15 02:19 UTC, merged